# Checkpoint 1 - Análise Covid Brasil

## Carregar módulos

In [ ]:
import numpy as np
import pandas as pd

## Carregar dados

- Dados Covid Brasil

In [ ]:
! wget --no-check-certificate --content-disposition 'https://github.com/wcota/covid19br/blob/master/cases-brazil-cities-time.csv.gz?raw=true'

--2021-08-29 20:55:35--  https://github.com/wcota/covid19br/blob/master/cases-brazil-cities-time.csv.gz?raw=true
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/wcota/covid19br/raw/master/cases-brazil-cities-time.csv.gz [following]
--2021-08-29 20:55:35--  https://github.com/wcota/covid19br/raw/master/cases-brazil-cities-time.csv.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv.gz [following]
--2021-08-29 20:55:35--  https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities-time.csv.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80581725 (77M) [application/octet-stream]
Saving to: ‘cases-brazil-cities-time.csv.gz’

cases-brazil-cities 100%[===================>]  76.85M   152MB/s    in 0.5s

2021-08-29 20:55:36 (152 MB/s) - ‘cases-brazil-cities-time.csv.gz’ saved [80581725/80581725]

In [ ]:
! gunzip cases-brazil-cities-time.csv.gz

In [ ]:
dados_brasil = pd.read_csv('cases-brazil-cities-time.csv')

- Dados censo

In [ ]:
dados_censo = pd.read_csv('dados_municipios_2010.csv', sep = ';', decimal = ',', encoding = 'latin1')

## Ajustar dados

In [ ]:
max_date = max(dados_brasil['date'])

In [ ]:
dados_brasil = dados_brasil[(dados_brasil['date'] == max_date) & \
                            (dados_brasil['state'] != 'TOTAL')]

In [ ]:
cols = ['ibgeID', 'date', 'state', 'city', 'totalCases', 'deaths']

In [ ]:
dados_brasil = dados_brasil[cols].reset_index(drop=True)

## Aqui começa o trabalho

- Bruno Biancchi - RM84351
- Luis Henrique Caldas Altero – RM88670
- Vitor Lamprecht  - RM86691

# Questão 1

- Quantas cidades existem em cada dataframe? (dados_municipios_gerais e dados_municipios_covid)?

Resposta: No dataframe dados_censo existem 5565 municípios e no dataframe dados_brasil existem 5596 municípios.

In [ ]:
dados_censo['ibgeID'].nunique()

5565

In [ ]:
dados_brasil['ibgeID'].nunique()

5596

# Questão 2

- Como realizar o join desses dataframes? (realizar o join!! Dica, usar a função pd.merge).
Indicar quais cidades não houve o join e retirar das análises.

Resposta: O dataframe dados_censo_covid informa as os dados comuns entre a tabela dados_brasil e dados_censo devido ao inner join. Já o dataframe dados_cidade_fora traz as os municipios que não houve join, devido ao uso da função 'left'.

In [ ]:
dados_censo_covid = pd.merge(dados_brasil, dados_censo, on = 'ibgeID', how = 'inner')
dados_censo_covid

       ibgeID        date state  ... T_ANALF18M    RDPC   IDHM
0     5200050  2021-08-27    GO  ...       8.36  574.96  0.708
1     3100104  2021-08-27    MG  ...       9.67  596.18  0.689
2     5200100  2021-08-27    GO  ...      11.67  519.87  0.689
3     1500107  2021-08-27    PA  ...      14.97  293.01  0.628
4     3100203  2021-08-27    MG  ...       9.28  707.24  0.698
...       ...         ...   ...  ...        ...     ...    ...
5560  4301552  2021-08-27    RS  ...       5.76  686.10  0.707
5561  4101150  2021-08-27    PR  ...      12.11  641.37  0.721
5562  2900504  2021-08-27    BA  ...      32.52  258.28  0.584
5563  1505106  2021-08-27    PA  ...      13.73  255.03  0.594
5564  3533809  2021-08-27    SP  ...       6.32  676.94  0.730

[5565 rows x 12 columns]

In [ ]:
dados_cidades_fora = dados_brasil.merge(dados_censo, on = 'ibgeID', how = 'left')
dados_cidades_fora = dados_cidades_fora.replace(np.nan,'municipio_faltando')
dados_cidades_fora = dados_cidades_fora[dados_cidades_fora['Municipio'] == 'municipio_faltando']
dados_cidades_fora

       ibgeID        date  ...                RDPC                IDHM
434   4220000  2021-08-27  ...  municipio_faltando  municipio_faltando
781        12  2021-08-27  ...  municipio_faltando  municipio_faltando
782        27  2021-08-27  ...  municipio_faltando  municipio_faltando
783        13  2021-08-27  ...  municipio_faltando  municipio_faltando
784        16  2021-08-27  ...  municipio_faltando  municipio_faltando
785        29  2021-08-27  ...  municipio_faltando  municipio_faltando
786        23  2021-08-27  ...  municipio_faltando  municipio_faltando
787        32  2021-08-27  ...  municipio_faltando  municipio_faltando
788        52  2021-08-27  ...  municipio_faltando  municipio_faltando
789        21  2021-08-27  ...  municipio_faltando  municipio_faltando
790        31  2021-08-27  ...  municipio_faltando  municipio_faltando
791        50  2021-08-27  ...  municipio_faltando  municipio_faltando
792        51  2021-08-27  ...  municipio_faltando  municipio_faltando
793        15  2021-08-27  ...  municipio_faltando  municipio_faltando
794        25  2021-08-27  ...  municipio_faltando  municipio_faltando
795        26  2021-08-27  ...  municipio_faltando  municipio_faltando
796        22  2021-08-27  ...  municipio_faltando  municipio_faltando
797        41  2021-08-27  ...  municipio_faltando  municipio_faltando
798        33  2021-08-27  ...  municipio_faltando  municipio_faltando
799        24  2021-08-27  ...  municipio_faltando  municipio_faltando
800        11  2021-08-27  ...  municipio_faltando  municipio_faltando
801        14  2021-08-27  ...  municipio_faltando  municipio_faltando
802        43  2021-08-27  ...  municipio_faltando  municipio_faltando
803        42  2021-08-27  ...  municipio_faltando  municipio_faltando
804        28  2021-08-27  ...  municipio_faltando  municipio_faltando
805        35  2021-08-27  ...  municipio_faltando  municipio_faltando
806        17  2021-08-27  ...  municipio_faltando  municipio_faltando
3101  1504752  2021-08-27  ...  municipio_faltando  municipio_faltando
3587  5006275  2021-08-27  ...  municipio_faltando  municipio_faltando
3742  4212650  2021-08-27  ...  municipio_faltando  municipio_faltando
3801  4314548  2021-08-27  ...  municipio_faltando  municipio_faltando

[31 rows x 12 columns]

# Questão 3

- – No dataset após o join, obter o índice de Gini por UF (state). Qual UF chamou atenção? Por
que isto ocorreu?

Resposta: O estado do Distrito Federal chamou atenção devido seu valor ser igual a zero, indicando uma igualdade perfeita, segundo o índice de gini. Isso ocorreu devido a existência de apenas um municipio nesse estado(Brasília), fazendo com que a comparação de Brasília fosse feita com ela mesma.Assim, indicando que o Gini não pode ser utilizado com apenas um local para ser analisado.

In [ ]:
def gini(array):
  array = array.flatten()
  if np.amin(array) < 0:
    array -= np.amin(array)
  array += 0.0000001
  array = np.sort(array)
  index = np.arange(1,array.shape[0]+1)
  n = array.shape[0]
  return ((np.sum((2 * index - n - 1)* array)) / (n * np.sum(array)))

In [ ]:
dados_gini_uf = dados_censo_covid.groupby('state')['RDPC'].apply(lambda x: gini(x.values)).to_frame().reset_index()
dados_gini_uf

   state      RDPC
0     AC  0.195495
1     AL  0.140823
2     AM  0.180262
3     AP  0.177035
4     BA  0.160275
5     CE  0.132551
6     DF  0.000000
7     ES  0.153020
8     GO  0.138104
9     MA  0.187907
10    MG  0.192143
11    MS  0.134532
12    MT  0.154616
13    PA  0.208619
14    PB  0.134084
15    PE  0.169153
16    PI  0.149203
17    PR  0.131235
18    RJ  0.146672
19    RN  0.144012
20    RO  0.127922
21    RR  0.241690
22    RS  0.153786
23    SC  0.137464
24    SE  0.140378
25    SP  0.140590
26    TO  0.173719

# Questão 4

- Obtenha o sumário das colunas por UF (state), similar a figura abaixo (apresentar o código):

In [ ]:
tabela_estado = dados_censo_covid.groupby('state').agg(CasosTotais = pd.NamedAgg('totalCases', 'sum'),
                                                     MortesTotais = pd.NamedAgg('deaths', 'sum'),
                                                     MediaESPVIDA = pd.NamedAgg('ESPVIDA', 'mean'),
                                                     MediaE_AnosESTUDO = pd.NamedAgg('E_ANOSESTUDO','mean'),
                                                     MediaT_ANALF18M = pd.NamedAgg('T_ANALF18M','mean'),
                                                     Mediana_IDHM = pd.NamedAgg('IDHM', 'median'),
                                                     Mediana_RDPC = pd.NamedAgg('RDPC','median'),
                                                     DP_RDPC = pd.NamedAgg('RDPC','std')    
                                                     ).reset_index()
tabela_estado

   state  CasosTotais  MortesTotais  ...  Mediana_IDHM  Mediana_RDPC     DP_RDPC
0     AC        87798          1813  ...        0.5885       313.705  127.780499
1     AL       235262          6048  ...        0.5625       233.440   79.124345
2     AM       423832         13674  ...        0.5640       227.585   98.250134
3     AP       122383          1950  ...        0.6410       402.440  133.018963
4     BA      1207512         26093  ...        0.5890       272.860  101.927806
5     CE       919136         23988  ...        0.6120       256.840   76.335807
6     DF       467693          9993  ...        0.8240      1715.110         NaN
7     ES       555779         11972  ...        0.6835       533.375  203.473289
8     GO       809948         22308  ...        0.6970       573.815  148.262560
9     MA       348215          9977  ...        0.5720       217.650   90.115351
10    MG      2053726         52431  ...        0.6700       475.230  173.077762
11    MS       367131          9318  ...        0.6830       588.945  147.065926
12    MT       514028         13190  ...        0.6860       550.290  165.772991
13    PA       581369         16402  ...        0.5830       279.190  119.240295
14    PB       432350          9165  ...        0.5830       263.840   92.074926
15    PE       606004         19345  ...        0.5930       271.360  117.490310
16    PI       316053          6941  ...        0.5650       229.600   76.019439
17    PR      1445836         37114  ...        0.7060       592.270  150.286289
18    RJ      1122331         62091  ...        0.7125       618.330  217.600292
19    RN       364695          7258  ...        0.6060       285.210   98.946556
20    RO       262676          6473  ...        0.6430       466.855  123.200293
21    RR       120799          1918  ...        0.6240       329.220  161.370173
22    RS      1405410         34108  ...        0.7170       714.125  207.996885
23    SC      1148544         18550  ...        0.7360       768.810  199.720910
24    SE       277367          5981  ...        0.5920       282.400  105.977056
25    SP      4243084        145316  ...        0.7380       686.890  197.398270
26    TO       218079          3670  ...        0.6390       347.030  132.179224

[27 rows x 9 columns]

# Questão 5

Resposta: Pode-se ver que o IDH dos estados não influenciam na quantidade de casos de covid e mortes, contudo, é possível notar que o IDH influencia na média de analfabetismo no estado (quanto maior o IDH do estado menor a média de analfabetismo presente) e na mediana de Renda per capita (quanto maior o IDH do estado maior a mediana de renda per capita).

In [ ]:
tabela_estado.sort_values('Mediana_IDHM')

   state  CasosTotais  MortesTotais  ...  Mediana_IDHM  Mediana_RDPC     DP_RDPC
1     AL       235262          6048  ...        0.5625       233.440   79.124345
2     AM       423832         13674  ...        0.5640       227.585   98.250134
16    PI       316053          6941  ...        0.5650       229.600   76.019439
9     MA       348215          9977  ...        0.5720       217.650   90.115351
13    PA       581369         16402  ...        0.5830       279.190  119.240295
14    PB       432350          9165  ...        0.5830       263.840   92.074926
0     AC        87798          1813  ...        0.5885       313.705  127.780499
4     BA      1207512         26093  ...        0.5890       272.860  101.927806
24    SE       277367          5981  ...        0.5920       282.400  105.977056
15    PE       606004         19345  ...        0.5930       271.360  117.490310
19    RN       364695          7258  ...        0.6060       285.210   98.946556
5     CE       919136         23988  ...        0.6120       256.840   76.335807
21    RR       120799          1918  ...        0.6240       329.220  161.370173
26    TO       218079          3670  ...        0.6390       347.030  132.179224
3     AP       122383          1950  ...        0.6410       402.440  133.018963
20    RO       262676          6473  ...        0.6430       466.855  123.200293
10    MG      2053726         52431  ...        0.6700       475.230  173.077762
11    MS       367131          9318  ...        0.6830       588.945  147.065926
7     ES       555779         11972  ...        0.6835       533.375  203.473289
12    MT       514028         13190  ...        0.6860       550.290  165.772991
8     GO       809948         22308  ...        0.6970       573.815  148.262560
17    PR      1445836         37114  ...        0.7060       592.270  150.286289
18    RJ      1122331         62091  ...        0.7125       618.330  217.600292
22    RS      1405410         34108  ...        0.7170       714.125  207.996885
23    SC      1148544         18550  ...        0.7360       768.810  199.720910
25    SP      4243084        145316  ...        0.7380       686.890  197.398270
6     DF       467693          9993  ...        0.8240      1715.110         NaN

[27 rows x 9 columns]